ForkliftServiseManagerOrganizer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('organizer.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/urls.py
from django.urls import path
from . import views

app_name = 'organizer'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_task', views.add_task, name='add-task'),
    path('customer_list', views.customer_list, name='customer-list'),
    path('customer', views.customer, name='customer'),
]

organizer/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Customer(models.Model):
    name = models.CharField(max_length=128, unique=True)
    legal_name = models.CharField(max_length=128, unique=True, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    caller = models.TextField(null=True, blank=True)
    lifting_equipment = models.TextField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def url(self):
        return reverse('organizer:customer-detail', kwargs={'pk': self.id})


class CustomerRequest(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='requests', default='1')
    customer = models.ForeignKey('Customer', on_delete=models.SET_NULL, blank=True, null=True, related_name='requests')
    date = models.DateTimeField(default=datetime.datetime.now)
    appeal = models.TextField(null=True, blank=True)
    end_of_work = models.BooleanField(default=False)
    agreed = models.BooleanField(default=False)

organizer/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'Index Page'
    }
    return render(request, template_name='organizer/index.html', context=context)


def add_task(request):
    context = {
        'title': 'Add task page'
    }
    return render(request, template_name='organizer/add_task.html', context=context)


def customer_list(request):
    context = {
        'title': 'customer list'
    }
    return render(
        request, template_name='organizer/customer_list.html', context=context)


def customer(request):
    context = {
        'title': 'customer'
    }
    return render(
        request, template_name='organizer/customer.html', context=context)

organizer/templates/organizer/add_task.html
{% extends 'organizer/base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center p-5">
    <div class="col-4"> <h3 class="text-center">Add task</h3> </div>    
  </div>
</div>


<form action="#">
    <div class="container border rounded">
        <div class="row justify-content-around">
            <div class="m-3 col-md-5 col-sm-12">
                <input type="text" class="form-control" placeholder="Enter customer name">
            </div>
            <div class="m-3 col-md-5 col-sm-12">
                <input type="text" class="form-control" placeholder="Enter customer name">
            </div>
        </div>
        <div class="m-3">
            <textarea name="" class="form-control col-xs-12"  rows="10"></textarea>
        </div>
        
        <div class="row justify-content-around">
            <div class="my-3 col-md-4 col-sm-12 text-center">
                <input type="checkbox" class="form-check-input" id="agreedCheck">
                <label class="form-check-label" for="agreedCheck">Agreed</label>
            </div>
            <div class="my-3 col-md-4 col-sm-12 text-center">
                <input type="checkbox" class="form-check-input" id="doneCheck">
                <label class="form-check-label" for="doneCheck">Done</label>
            </div>
            <div class="my-3 col-md-4 col-sm-12 text-center">
                <input type="checkbox" class="form-check-input" id="onemoreCheck">
                <label class="form-check-label" for="onemoreCheck">Onemore</label>
            </div>
        </div>
        <div class="my-3 text-center">
            <button type="submit" class="btn btn-primary mx-auto">Submit</button>
        </div>
    </div>
  </form>
{% endblock %}

organizer/templates/organizer/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'organizer/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'organizer/img/fav.png' '%}" type="image/png">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'organizer:index' %}"><img src="{% static 'organizer/img/customer-support.png' %}" alt="" width="30"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#bootstrap-navbars" aria-controls="bootstrap-navbars" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="bootstrap-navbars">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Active tasks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">In work</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Task archive</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'organizer:customer-list' %}">Customers</a>
                    </li>
                </ul>
                <form>
                    <input class="form-control" type="text" placeholder="Search customer" aria-label="Search">
                </form>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>

</html>

organizer/templates/organizer/customer.html
{% extends 'organizer/base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center p-5">
    <div class="col-4"> <h3 class="text-center">{{ customer.name }}</h3> </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <h1>Customer Page</h1>
  </div>
</div>

{% endblock %}

organizer/templates/organizer/customer_list.html
{% extends 'organizer/base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center p-5">
    <div class="col-4"> <h3 class="text-center">Customer list</h3> </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="{% url 'organizer:customer' %}">
        Customer name
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="{% url 'organizer:customer' %}">
        Customer name
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="{% url 'organizer:customer' %}">
        Customer name
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="{% url 'organizer:customer' %}">
        Customer name
      </a>
    </div>
  </div>
</div>
{% endblock %}

organizer/templates/organizer/index.html
{% extends 'organizer/base.html' %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row justify-content-center p-5">
    <div class="col-4 mt-20"> <h3 class="text-center">Active tasks</h3> </div>    
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12 m-3 d-flex align-items-center justify-content-center" style="width:180px ;height:120px">
      <a href="{% url 'organizer:add-task' %}"><img src="{% static 'organizer/img/plus.png' %}" alt="" width="80"></a>
    </div>
    
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12  m-3 p-0" style="width:180px ;height:120px">
      <a href="#">
        <div class="container p-0 align-items-center mt-2">
          <div class="row text-center">
            <h5>23.01.20</h5>
          </div>
          <div class="row text-center">
            <p>Customer name</p>
          </div>
          <div class="row text-center">
            <p>Type of work</p>
          </div>
        </div>
      </a>
    </div>
  </div>
</div>
{% endblock %}